src/Entity/FosUser.php
<?php

namespace App\Entity;

use App\Repository\FosUserRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FosUserRepository::class)
 */
class FosUser
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username_canonice;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email_canonical;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $enabled;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $salt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_login;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $confirmation_token;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password_requeste;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_activity;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel_nr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mobile_nr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firs_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $insertion_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;



    /**
     * @ORM\Column(type="string", length=255)
     */
    private $function;

    /**
     * @ORM\ManyToOne(targetEntity=organisation::class)
     */
    private $organisation_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getUsernameCanonice(): ?string
    {
        return $this->username_canonice;
    }

    public function setUsernameCanonice(string $username_canonice): self
    {
        $this->username_canonice = $username_canonice;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getEmailCanonical(): ?string
    {
        return $this->email_canonical;
    }

    public function setEmailCanonical(string $email_canonical): self
    {
        $this->email_canonical = $email_canonical;

        return $this;
    }

    public function getEnabled(): ?string
    {
        return $this->enabled;
    }

    public function setEnabled(string $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getSalt(): ?string
    {
        return $this->salt;
    }

    public function setSalt(string $salt): self
    {
        $this->salt = $salt;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getLastLogin(): ?string
    {
        return $this->last_login;
    }

    public function setLastLogin(string $last_login): self
    {
        $this->last_login = $last_login;

        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmation_token;
    }

    public function setConfirmationToken(string $confirmation_token): self
    {
        $this->confirmation_token = $confirmation_token;

        return $this;
    }

    public function getPasswordRequeste(): ?string
    {
        return $this->password_requeste;
    }

    public function setPasswordRequeste(string $password_requeste): self
    {
        $this->password_requeste = $password_requeste;

        return $this;
    }

    public function getRoles(): ?string
    {
        return $this->roles;
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getLastActivity(): ?string
    {
        return $this->last_activity;
    }

    public function setLastActivity(string $last_activity): self
    {
        $this->last_activity = $last_activity;

        return $this;
    }

    public function getTelNr(): ?string
    {
        return $this->tel_nr;
    }

    public function setTelNr(string $tel_nr): self
    {
        $this->tel_nr = $tel_nr;

        return $this;
    }

    public function getMobileNr(): ?string
    {
        return $this->mobile_nr;
    }

    public function setMobileNr(string $mobile_nr): self
    {
        $this->mobile_nr = $mobile_nr;

        return $this;
    }

    public function getFirsName(): ?string
    {
        return $this->firs_name;
    }

    public function setFirsName(string $firs_name): self
    {
        $this->firs_name = $firs_name;

        return $this;
    }

    public function getInsertionName(): ?string
    {
        return $this->insertion_name;
    }

    public function setInsertionName(string $insertion_name): self
    {
        $this->insertion_name = $insertion_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(string $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }



    public function getFunction(): ?string
    {
        return $this->function;
    }

    public function setFunction(string $function): self
    {
        $this->function = $function;

        return $this;
    }

    public function getOrganisationId(): ?Organisation
    {
        return $this->organisation_id;
    }

    public function setOrganisationId(?Organisation $organisation_id): self
    {
        $this->organisation_id = $organisation_id;

        return $this;
    }
}

src/Form/FosUserType.php
<?php

namespace App\Form;

use App\Entity\FosUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FosUserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('username_canonice')
            ->add('email')
            ->add('email_canonical')
            ->add('enabled')
            ->add('salt')
            ->add('password')
            ->add('last_login')
            ->add('confirmation_token')
            ->add('password_requeste')
            ->add('roles')
            ->add('last_activity')
            ->add('tel_nr')
            ->add('mobile_nr')
            ->add('firs_name')
            ->add('insertion_name')
            ->add('last_name')
            ->add('adress')
            ->add('zip')
            ->add('city')
            ->add('country')
            ->add('function')
            ->add('organisation_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FosUser::class,
        ]);
    }
}

src/Controller/FosUserController.php
<?php

namespace App\Controller;

use App\Entity\FosUser;
use App\Form\FosUserType;
use App\Repository\FosUserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/fos/user")
 */
class FosUserController extends AbstractController
{
    /**
     * @Route("/", name="fos_user_index", methods={"GET"})
     */
    public function index(FosUserRepository $fosUserRepository): Response
    {
        return $this->render('fos_user/index.html.twig', [
            'fos_users' => $fosUserRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="fos_user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $fosUser = new FosUser();
        $form = $this->createForm(FosUserType::class, $fosUser);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($fosUser);
            $entityManager->flush();

            return $this->redirectToRoute('fos_user_index');
        }

        return $this->render('fos_user/new.html.twig', [
            'fos_user' => $fosUser,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fos_user_show", methods={"GET"})
     */
    public function show(FosUser $fosUser): Response
    {
        return $this->render('fos_user/show.html.twig', [
            'fos_user' => $fosUser,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="fos_user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, FosUser $fosUser): Response
    {
        $form = $this->createForm(FosUserType::class, $fosUser);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('fos_user_index');
        }

        return $this->render('fos_user/edit.html.twig', [
            'fos_user' => $fosUser,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fos_user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, FosUser $fosUser): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fosUser->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($fosUser);
            $entityManager->flush();
        }

        return $this->redirectToRoute('fos_user_index');
    }
}

templates/fos_user/_delete_form.html.twig
<form method="post" action="{{ path('fos_user_delete', {'id': fos_user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fos_user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fos_user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fos_user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FosUser{% endblock %}

{% block body %}
    <h1>Edit FosUser</h1>

    {{ include('fos_user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('fos_user_index') }}">back to list</a>

    {{ include('fos_user/_delete_form.html.twig') }}
{% endblock %}

templates/fos_user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FosUser index{% endblock %}

{% block body %}
    <h1>FosUser index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Username_canonice</th>
                <th>Email</th>
                <th>Email_canonical</th>
                <th>Enabled</th>
                <th>Salt</th>
                <th>Password</th>
                <th>Last_login</th>
                <th>Confirmation_token</th>
                <th>Password_requeste</th>
                <th>Roles</th>
                <th>Last_activity</th>
                <th>Tel_nr</th>
                <th>Mobile_nr</th>
                <th>Firs_name</th>
                <th>Insertion_name</th>
                <th>Last_name</th>
                <th>Adress</th>
                <th>Zip</th>
                <th>City</th>
                <th>Country</th>
                <th>Function</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fos_user in fos_users %}
            <tr>
                <td>{{ fos_user.id }}</td>
                <td>{{ fos_user.username }}</td>
                <td>{{ fos_user.usernameCanonice }}</td>
                <td>{{ fos_user.email }}</td>
                <td>{{ fos_user.emailCanonical }}</td>
                <td>{{ fos_user.enabled }}</td>
                <td>{{ fos_user.salt }}</td>
                <td>{{ fos_user.password }}</td>
                <td>{{ fos_user.lastLogin }}</td>
                <td>{{ fos_user.confirmationToken }}</td>
                <td>{{ fos_user.passwordRequeste }}</td>
                <td>{{ fos_user.roles }}</td>
                <td>{{ fos_user.lastActivity }}</td>
                <td>{{ fos_user.telNr }}</td>
                <td>{{ fos_user.mobileNr }}</td>
                <td>{{ fos_user.firsName }}</td>
                <td>{{ fos_user.insertionName }}</td>
                <td>{{ fos_user.lastName }}</td>
                <td>{{ fos_user.adress }}</td>
                <td>{{ fos_user.zip }}</td>
                <td>{{ fos_user.city }}</td>
                <td>{{ fos_user.country }}</td>
                <td>{{ fos_user.function }}</td>
                <td>
                    <a href="{{ path('fos_user_show', {'id': fos_user.id}) }}">show</a>
                    <a href="{{ path('fos_user_edit', {'id': fos_user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="24">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('fos_user_new') }}">Create new</a>
{% endblock %}

templates/fos_user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FosUser{% endblock %}

{% block body %}
    <h1>Create new FosUser</h1>

    {{ include('fos_user/_form.html.twig') }}

    <a href="{{ path('fos_user_index') }}">back to list</a>
{% endblock %}

templates/fos_user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FosUser{% endblock %}

{% block body %}
    <h1>FosUser</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fos_user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ fos_user.username }}</td>
            </tr>
            <tr>
                <th>Username_canonice</th>
                <td>{{ fos_user.usernameCanonice }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ fos_user.email }}</td>
            </tr>
            <tr>
                <th>Email_canonical</th>
                <td>{{ fos_user.emailCanonical }}</td>
            </tr>
            <tr>
                <th>Enabled</th>
                <td>{{ fos_user.enabled }}</td>
            </tr>
            <tr>
                <th>Salt</th>
                <td>{{ fos_user.salt }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ fos_user.password }}</td>
            </tr>
            <tr>
                <th>Last_login</th>
                <td>{{ fos_user.lastLogin }}</td>
            </tr>
            <tr>
                <th>Confirmation_token</th>
                <td>{{ fos_user.confirmationToken }}</td>
            </tr>
            <tr>
                <th>Password_requeste</th>
                <td>{{ fos_user.passwordRequeste }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ fos_user.roles }}</td>
            </tr>
            <tr>
                <th>Last_activity</th>
                <td>{{ fos_user.lastActivity }}</td>
            </tr>
            <tr>
                <th>Tel_nr</th>
                <td>{{ fos_user.telNr }}</td>
            </tr>
            <tr>
                <th>Mobile_nr</th>
                <td>{{ fos_user.mobileNr }}</td>
            </tr>
            <tr>
                <th>Firs_name</th>
                <td>{{ fos_user.firsName }}</td>
            </tr>
            <tr>
                <th>Insertion_name</th>
                <td>{{ fos_user.insertionName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ fos_user.lastName }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ fos_user.adress }}</td>
            </tr>
            <tr>
                <th>Zip</th>
                <td>{{ fos_user.zip }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ fos_user.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ fos_user.country }}</td>
            </tr>
            <tr>
                <th>Function</th>
                <td>{{ fos_user.function }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('fos_user_index') }}">back to list</a>

    <a href="{{ path('fos_user_edit', {'id': fos_user.id}) }}">edit</a>

    {{ include('fos_user/_delete_form.html.twig') }}
{% endblock %}